"""Generate the fixed V3-L/mask-0 tables; reference: vendor/qrcodegen.py (MIT).

Run from any directory. The reference is vendored so regeneration is offline.
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'tools/vendor'))
from qrcodegen import QrCode


def profile(version):
    size = 4 * version + 17
    ecc = QrCode.Ecc.MEDIUM if version == 2 else QrCode.Ecc.LOW
    qr = QrCode.__new__(QrCode)
    qr._version, qr._size, qr._errcorlvl = version, size, ecc
    qr._modules = [[False] * size for _ in range(size)]
    qr._isfunction = [[False] * size for _ in range(size)]
    qr._draw_function_patterns()
    qr._draw_format_bits(0)
    qr._apply_mask(0)

    def bitmap(matrix):
        out = bytearray((size * size + 7) // 8)
        for y in range(size):
            for x in range(size):
                if matrix[y][x]:
                    bit = y * size + x
                    out[bit // 8] |= 1 << (bit % 8)
        return out

    logs, powers = [0] * 256, []
    value = 1
    for i in range(255):
        logs[value] = i
        powers.append(value)
        value = QrCode._reed_solomon_multiply(value, 2)
    powers.append(1)
    arrays = [('qr_template', bitmap(qr._modules)),
              ('qr_reserved', bitmap(qr._isfunction)),
              ('qr_divisor', QrCode._reed_solomon_compute_divisor(16 if version == 2 else 15)),
              ('qr_log', logs), ('qr_exp', powers)]
    lines = ['/* Generated by tools/generate_tables.py. Do not edit.',
             ' * Derived using Project Nayuki (MIT), tools/vendor/qrcodegen.py.',
             ' * Generated fixed-mask tables for profile %d.' % version,
             ' */']
    for name, values in arrays:
        lines.append('static const u8 %s[%d] = {' % (name, len(values)))
        for i in range(0, len(values), 16):
            lines.append('    ' + ', '.join('0x%02Xu' % n for n in values[i:i+16]) + ',')
        lines.append('};')
    return '\n'.join(lines) + '\n'


def generate():
    return '#if NGPC_QR_PROFILE == 2\n' + profile(2) + '#else\n' + profile(3) + '#endif\n'


if __name__ == '__main__':
    target = ROOT / 'ngpc_qr_tables.h'
    content = generate()
    if '--check' in sys.argv:
        assert target.read_text() == content, 'QR tables need regeneration'
        print('QR tables match vendored reference')
    else:
        target.write_text(content, encoding='ascii')
        print(target)
