/* Generated by tools/gen/course_markers.py. */
#ifndef ID_BORNE_INCLUDED
#define ID_BORNE_INCLUDED
#include "ngpc_types.h"
#define ID_BORNE_STYLES 1u
#define ID_BORNE_STEPS 5u
#define ID_BORNE_CHARS 8u
extern const u16 id_borne_tiles[64];
extern const u16 id_borne_palette[4];
extern const u8 id_borne_px_w[5];
extern const u8 id_borne_first[5];
extern const u8 id_borne_w[5];
extern const u8 id_borne_h[5];
#endif
