/* Generated by tools/export_car_png.py -- do not edit. */
#ifndef ID_CAROG_H
#define ID_CAROG_H

#include "ngpc_types.h"

#ifndef ID_CAR_CELL_DEFINED
#define ID_CAR_CELL_DEFINED
typedef struct { u8 cx, cy, ch; } IdCarCell;
#endif

/* SIX VUES, DE L'ARRIERE A L'AVANT : un DEMI-tour. L'autre moitie
 * est la meme chose par le bit H-flip du sprite, ce qui ne coute
 * pas un caractere. Dix positions en tout pour un tour complet.
 *
 * La pose 0 est l'arriere, celle que la course dessine ; la pose 1
 * est un trois-quarts arriere, donc l'inclinaison en virage. */
#define ID_CAROG_LAYERS  2
#define ID_CAROG_POSES   6
#define ID_CAROG_HEIGHT  16
#define ID_CAROG_ANGLES  10

/* CE QUE LA COURSE DOIT CHARGER, et pas un caractere de plus.
 * id_car_draw() borne la pose a 2 : au-dela, c'est le demi-tour
 * du garage. Les caracteres des trois premieres vues des DEUX
 * couches sont groupes en tete de la table pour que ce prefixe
 * suffise ; le garage, lui, charge tout. */
#define ID_CAROG_RACE_POSES  3
#define ID_CAROG_RACE_CHARS  29

extern const u16 id_carog_tiles_count;
extern const u16 id_carog_tiles[];
extern const u16 id_carog_palette[8];
extern const u8  id_carog_pose_cells[];
extern const u8  id_carog_pose_first[];
extern const u8  id_carog_pose_w[];
extern const IdCarCell id_carog_cells[];

#endif
